HTML = r'''<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ClipForge</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#090a0f;color:#f7f7fb;font:15px system-ui,-apple-system,Segoe UI,sans-serif}
main{max-width:1120px;margin:auto;padding:32px 18px 90px}.hero{padding:48px 0 24px}.tag{font-size:12px;font-weight:900;letter-spacing:.14em;color:#9f7aea}
h1{font-size:clamp(44px,9vw,82px);line-height:.94;margin:12px 0}h1 span{color:#9b6cff}h2{margin:0 0 8px;font-size:19px}
p{color:#a5a9b8;line-height:1.6}.card{margin:16px 0;padding:22px;border:1px solid #2b2f3d;border-radius:18px;background:#12141b}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.btn,button{border:0;border-radius:11px;padding:12px 16px;background:#835dff;color:white;font-weight:850;text-decoration:none;cursor:pointer}
.secondary{background:#242733}.ghost{background:transparent;border:1px solid #3a4050}.danger{background:#612a34}.pill{border:1px solid #343948;border-radius:999px;padding:8px 11px;color:#adb2c2;font-size:12px}
code{display:block;padding:12px;background:#0c0e13;border:1px solid #292d3a;border-radius:9px;overflow:auto}input{background:#0d0f15;color:#fff;border:1px solid #333847;border-radius:10px;padding:11px 12px;font:inherit}
input[type=text]{min-width:240px;flex:1}input[type=number]{width:92px}.clips{display:grid;gap:11px;margin-top:15px}.clip{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;padding:15px;border:1px solid #2e3342;background:#191c25;border-radius:13px}
.score{font-size:25px;font-weight:900;color:#5ce6a5}.small{font-size:12px;color:#9299aa}.creator{color:#b8a6ff;font-weight:800}.hidden{display:none!important}.warn{color:#ffd274}.selected{outline:2px solid #835dff}
.editorItem{padding:14px;border:1px solid #343949;background:#171a22;border-radius:14px;margin:10px 0}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.grid label{font-size:12px;color:#9da3b3}.grid input{width:100%;margin-top:5px}
video{width:min(360px,100%);aspect-ratio:9/16;background:#000;border-radius:16px}.download{display:inline-block;margin-top:12px}
.tabs{display:flex;gap:8px;margin:6px 0 20px;padding:6px;background:#11131a;border:1px solid #2b2f3d;border-radius:15px;position:sticky;top:10px;z-index:20;backdrop-filter:blur(12px)}
.tab{flex:1;background:transparent;color:#aeb3c2;border:1px solid transparent;padding:13px 16px}.tab.active{background:#242733;color:white;border-color:#3b4152}.tabBadge{margin-left:7px;background:#835dff;border-radius:999px;padding:2px 7px;font-size:11px;color:white}.tabPanel{display:none}.tabPanel.active{display:block}.editorHero{display:flex;gap:16px;align-items:flex-start;justify-content:space-between}.editorHero p{margin:4px 0 0}.emptyEditor{text-align:center;padding:46px 18px;border:1px dashed #3a4050;border-radius:16px;color:#9299aa}
@media(max-width:760px){.clip{grid-template-columns:1fr auto}.clip .actions{grid-column:1/3}.grid{grid-template-columns:1fr 1fr}.hero{padding-top:28px}.tabs{top:6px}.editorHero{display:block}}
</style>
</head>
<body><main>
<section class="hero"><div class="tag">TWITCH → CLIP SCOUT → SHORT EDITOR</div><h1>ClipForge <span>Web</span></h1><p>Scout clips, select several moments, then switch to the editor tab to arrange, trim, render, and download your finished Short.</p><div class="row"><a class="btn" href="/auth/twitch">Connect Twitch</a><button class="secondary" onclick="scanMine('demo')">Try demo</button><span class="pill" id="status">Checking…</span></div></section>

<nav class="tabs" aria-label="ClipForge sections">
<button id="clipsTab" class="tab active" onclick="showTab('clips')">Clip Scout</button>
<button id="editorTab" class="tab" onclick="showTab('editor')">Short Editor <span id="tabSelectedCount" class="tabBadge hidden">0</span></button>
</nav>

<section id="clipsPanel" class="tabPanel active">
<div class="card" id="setup"><h2>One-time Twitch setup</h2><p>Add this exact callback URL to your Twitch Developer app, then add TWITCH_CLIENT_ID and TWITCH_CLIENT_SECRET in Render.</p><code id="callback">Loading…</code></div>
<div class="card"><h2>Scout other Twitch channels</h2><p>Enter up to 10 usernames. ClipForge ranks their recent public clips. You can select them for a project, but rendering requires that your connected Twitch account is that broadcaster or an authorized editor.</p><div class="row"><input id="channels" type="text" placeholder="example: shroud, tarik, pokimane"><button onclick="scout()">Scan channels</button></div><div id="scoutClips" class="clips"><p>No channels scanned yet.</p></div></div>
<div class="card"><div class="row"><h2 style="margin-right:auto">My best clips</h2><button onclick="scanMine('live')">Scan my Twitch</button><button class="secondary" onclick="scanMine('demo')">Demo scan</button></div><div id="clips" class="clips"><p>No clips scanned yet.</p></div></div>
<div class="card"><div class="row"><div><b id="selectionSummary">No clips selected</b><div class="small">Select up to 10 clips, then move to the editor.</div></div><button style="margin-left:auto" onclick="showTab('editor')">Edit selected clips →</button></div></div>
</section>

<section id="editorPanel" class="tabPanel">
<div class="card">
<div class="editorHero"><div><h2>Short Editor</h2><p>Arrange your selected clips, trim each moment, add text, then render one vertical Short.</p></div><span class="pill" id="selectedCount">0 clips selected</span></div>
<div class="row" style="margin-top:16px"><input id="globalHook" type="text" maxlength="60" placeholder="Main hook text, e.g. THIS ESCALATED FAST 💀"><button class="secondary" onclick="clearSelection()">Clear all</button><button class="ghost" onclick="showTab('clips')">+ Add more clips</button></div>
<div id="editorList" style="margin-top:16px"><div class="emptyEditor">No clips selected yet.<br><br><button onclick="showTab('clips')">Go select clips</button></div></div>
<div class="row" style="margin-top:16px"><button onclick="renderProject()">Render selected clips</button><span id="renderStatus" class="small"></span></div>
<div id="result" class="hidden" style="margin-top:18px"><video id="video" controls></video><br><a id="downloadBtn" class="btn download" href="#" download="clipforge-short.mp4">Download edited MP4</a></div>
</div>
</section>
</main><script>
let clips=[],scoutClips=[],selected=[];const $=id=>document.getElementById(id);function esc(s){return String(s||'').replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}async function api(url,opt={}){const r=await fetch(url,opt);const j=await r.json().catch(()=>({detail:r.statusText||"Request failed"}));if(!r.ok)throw Error(j.detail||"Request failed");return j}
function showTab(name){const editor=name==='editor';$('clipsPanel').classList.toggle('active',!editor);$('editorPanel').classList.toggle('active',editor);$('clipsTab').classList.toggle('active',!editor);$('editorTab').classList.toggle('active',editor);window.scrollTo({top:0,behavior:'smooth'});if(editor)renderEditor()}
async function boot(){try{const s=await api('/api/status');$('status').textContent=s.connected?'Twitch connected ✓':'Twitch not connected';$('callback').textContent=s.callback;if(s.connected)$('setup').classList.add('hidden')}catch(e){$('status').textContent='Server error'}}function idx(id){return selected.findIndex(x=>x.id===id)}
function card(c,i,source){const creator=c.broadcaster_name?`<span class="creator">${esc(c.broadcaster_name)}</span> · `:'';const open=c.url?`<a class="btn ghost" target="_blank" rel="noopener" href="${esc(c.url)}">Open Twitch</a>`:'';const on=idx(c.id)>=0;return `<div class="clip ${on?'selected':''}"><div><b>${esc(c.title)}</b><div class="small">${creator}${Number(c.view_count).toLocaleString()} views · ${Number(c.duration).toFixed(1)}s · ${esc(c.reason)}</div></div><div class="score">${c.score}</div><div class="actions row">${open}<button class="${on?'secondary':''}" onclick="toggleSelect('${source}',${i})">${on?'Selected ✓':'Select clip'}</button></div></div>`}function redraw(){if(clips.length)$('clips').innerHTML=clips.map((c,i)=>card(c,i,'mine')).join('');if(scoutClips.length)$('scoutClips').innerHTML=scoutClips.map((c,i)=>card(c,i,'scout')).join('')}
async function scanMine(mode){showTab('clips');$('clips').innerHTML='<p>Scanning…</p>';try{const d=await api('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode})});clips=d.clips||[];$('clips').innerHTML=clips.map((c,i)=>card(c,i,'mine')).join('')||'<p>No clips found.</p>'}catch(e){$('clips').innerHTML=`<p class="warn">${esc(e.message)}</p>`}}async function scout(){const raw=$('channels').value.trim();if(!raw){$('scoutClips').innerHTML='<p class="warn">Enter at least one Twitch channel.</p>';return}$('scoutClips').innerHTML='<p>Scanning channels…</p>';try{const d=await api('/api/scout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({channels:raw})});scoutClips=d.clips||[];$('scoutClips').innerHTML=scoutClips.map((c,i)=>card(c,i,'scout')).join('')||'<p>No recent clips found.</p>'}catch(e){$('scoutClips').innerHTML=`<p class="warn">${esc(e.message)}</p>`}}
function toggleSelect(source,i){const c=source==='scout'?scoutClips[i]:clips[i],j=idx(c.id);if(j>=0)selected.splice(j,1);else if(selected.length<10)selected.push({...c,trim_start:0,trim_end:Math.min(Number(c.duration)||20,20),overlay:''});else alert('You can use up to 10 clips.');renderEditor();redraw()}function clearSelection(){selected=[];renderEditor();redraw()}function moveItem(i,d){const j=i+d;if(j<0||j>=selected.length)return;[selected[i],selected[j]]=[selected[j],selected[i]];renderEditor()}function removeItem(i){selected.splice(i,1);renderEditor();redraw()}function setField(i,k,v){selected[i][k]=(k==='trim_start'||k==='trim_end')?Math.max(0,Number(v)||0):v}
function renderEditor(){const count=selected.length;$('selectedCount').textContent=`${count} clip${count===1?'':'s'} selected`;$('selectionSummary').textContent=count?`${count} clip${count===1?'':'s'} ready to edit`:'No clips selected';$('tabSelectedCount').textContent=count;$('tabSelectedCount').classList.toggle('hidden',count===0);if(!count){$('editorList').innerHTML='<div class="emptyEditor">No clips selected yet.<br><br><button onclick="showTab(\'clips\')">Go select clips</button></div>';return}$('editorList').innerHTML=selected.map((c,i)=>`<div class="editorItem"><div class="row"><b style="margin-right:auto">${i+1}. ${esc(c.broadcaster_name?c.broadcaster_name+' — ':'')}${esc(c.title)}</b><button class="ghost" onclick="moveItem(${i},-1)">↑</button><button class="ghost" onclick="moveItem(${i},1)">↓</button><button class="danger" onclick="removeItem(${i})">Remove</button></div><div class="grid"><label>Trim start<input type="number" min="0" step="0.1" value="${Number(c.trim_start).toFixed(1)}" onchange="setField(${i},'trim_start',this.value)"></label><label>Trim end<input type="number" min="0.1" step="0.1" value="${Number(c.trim_end).toFixed(1)}" onchange="setField(${i},'trim_end',this.value)"></label><label style="grid-column:span 2">Clip text<input type="text" maxlength="55" value="${esc(c.overlay||'')}" placeholder="optional caption" onchange="setField(${i},'overlay',this.value)"></label></div><div class="small">Original: ${Number(c.duration).toFixed(1)}s · ViralScore ${c.score}</div></div>`).join('')}
async function renderProject(){if(!selected.length){$('renderStatus').textContent='Select at least one clip.';return}$('renderStatus').textContent='Rendering your Short…';$('result').classList.add('hidden');try{const d=await api('/api/project/render',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({hook:$('globalHook').value.trim(),items:selected})});$('video').src=d.media_url+'?t='+Date.now();$('downloadBtn').href=d.download_url;$('result').classList.remove('hidden');$('renderStatus').textContent=`Ready ✓ ${d.duration.toFixed(1)}s`}catch(e){$('renderStatus').textContent=e.message}}boot();renderEditor();
</script></body></html>'''